options:
  open-port:
    type: int
    default: 8888
    description: "The port that is used to access jupyter notebook"
  pip3-dependencies:
    type: string
    default: "matplotlib pandas"
    description: "Python 3 pip dependencies to be installed together with the notebook"
